collector: print errors with debug formatter.
Anyhow has a good way of wrapping errors and add context to them: the
Context trait.

By using it, collectors can yield "collector-level" errors that wrap
even lower errors and they all get printed nicely, e.g:

$ retis -p generic collect -c ovs --ovs-enrich-flows
Applying profile generic
Error: Could not initialize the Ovs collector

Caused by:
    0: Failed to connect to OpenvSwitch
    1: No such file or directory (os error 2)

Signed-off-by: Adrian Moreno <amorenoz@redhat.com>