Makefile: fix install target.
Since 8c796182bb3c ("tree: make retis a workspace") files were moved
around to accomodate the new workspace structure. Because of that install
target stopped working with the following error:

[...]
[CARGO] building retis (release) ...
error: found a virtual manifest at `[...]/retis/Cargo.toml` instead
  of a package manifest
make: *** [Makefile:63: install] Error 101

Fix it specifying the updated path to cargo install.

Fixes: 8c796182bb3c ("tree: make retis a workspace")
Signed-off-by: Paolo Valerio <pvalerio@redhat.com>