rust/bindings: fix binding generation by including the types
Include vmlinux.h first in order to have required definitions available in the
bindgen run.

Below an excerpt of the error and the headers involved:

[BINDINGS]   processing [...]/retis-org/retis/retis/src/module/ovs/bpf/include/ovs_common.h ...
[...]/retis-org/retis/retis/src/.out/bpf/bpf_helper_defs.h:86:90: error: unknown type name '__u64'
[...]/retis-org/retis/retis/src/.out/bpf/bpf_helper_defs.h:110:49: error: unknown type name '__u32'
[...]/retis-org/retis/retis/src/.out/bpf/bpf_helper_defs.h:122:23: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
[...]

Reported-by: Andreas Karis <ak.karis@gmail.com>
Signed-off-by: Paolo Valerio <pvalerio@redhat.com>